export const usersData = [
    { firstName: 'Иван', lastName: 'Иванов', age: 25 },
    { firstName: 'Мария', lastName: 'Петрова', age: 30 },
    { firstName: 'Иван', lastName: 'Иванов', age: 25 },
    { firstName: 'Мария', lastName: 'Петрова', age: 30 },
    { firstName: 'Иван', lastName: 'Иванов', age: 25 },
    { firstName: 'Мария', lastName: 'Петрова', age: 30 },
    { firstName: 'Иван', lastName: 'Иванов', age: 25 },
    { firstName: 'Мария', lastName: 'Петрова', age: 30 },
    { firstName: 'Иван', lastName: 'Иванов', age: 25 },
    { firstName: 'Мария', lastName: 'Петрова', age: 30 },
    // Добавьте другие объекты с данными по мере необходимости
  ];
    
export const passengers = [
    {
    id: 1,
    class: "1",
    survived: true,
    name: "Allen, Miss. Elisabeth Walton",
    gender: "female",
    age: 29,
    sibsp: "0",
    parch: "0",
    ticket: "24160",
    fare: "211.3375",
    cabin: "B5",
    embarked: "S",
    boat: "2",
    body: null,
    'home.dest': "St Louis, MO"
    },
    {
    id: 2,
    class: "1",
    survived: true,
    name: "Allison, Master. Hudson Trevor",
    gender: "male",
    age: 0.9167,
    sibsp: "1",
    parch: "2",
    ticket: "113781",
    fare: "151.55",
    cabin: "C22 C26",
    embarked: "S",
    boat: "11",
    body: null,
    "home.dest": "Montreal, PQ / Chesterville, ON"
    },
    {
    id: 3,
    class: "1",
    survived: false,
    name: "Allison, Miss. Helen Loraine",
    gender: "female",
    age: 2,
    sibsp: "1",
    parch: "2",
    ticket: "113781",
    fare: "151.55",
    cabin: "C22 C26",
    embarked: "S",
    boat: null,
    body: null,
    "home.dest": "Montreal, PQ / Chesterville, ON"
    },
    {
    id: 4,
    class: "1",
    survived: false,
    name: "Allison, Mr. Hudson Joshua Creighton",
    gender: "male",
    age: 30,
    sibsp: "1",
    parch: "2",
    ticket: "113781",
    fare: "151.55",
    cabin: "C22 C26",
    embarked: "S",
    boat: null,
    body: "135",
    "home.dest": "Montreal, PQ / Chesterville, ON"
    },
    {
    id: 5,
    class: "1",
    survived: false,
    name: "Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",
    gender: "female",
    age: 25,
    sibsp: "1",
    parch: "2",
    ticket: "113781",
    fare: "151.55",
    cabin: "C22 C26",
    embarked: "S",
    boat: null,
    body: null,
    "home.dest": "Montreal, PQ / Chesterville, ON"
    },  
    {
    id: 6,
    class: "1",
    survived: true,
    name: "Anderson, Mr. Harry",
    gender: "male",
    age: 48,
    sibsp: "0",
    parch: "0",
    ticket: "19952",
    fare: "26.55",
    cabin: "E12",
    embarked: "S",
    boat: "3",
    body: null,
    "home.dest": "New York, NY"
    },
    {
    id: 1,
    class: "1",
    survived: true,
    name: "Allen, Miss. Elisabeth Walton",
    gender: "female",
    age: 29,
    sibsp: "0",
    parch: "0",
    ticket: "24160",
    fare: "211.3375",
    cabin: "B5",
    embarked: "S",
    boat: "2",
    body: null,
    'home.dest': "St Louis, MO"
    },
    {
    id: 2,
    class: "1",
    survived: true,
    name: "Allison, Master. Hudson Trevor",
    gender: "male",
    age: 0.9167,
    sibsp: "1",
    parch: "2",
    ticket: "113781",
    fare: "151.55",
    cabin: "C22 C26",
    embarked: "S",
    boat: "11",
    body: null,
    "home.dest": "Montreal, PQ / Chesterville, ON"
    },
    {
    id: 3,
    class: "1",
    survived: false,
    name: "Allison, Miss. Helen Loraine",
    gender: "female",
    age: 2,
    sibsp: "1",
    parch: "2",
    ticket: "113781",
    fare: "151.55",
    cabin: "C22 C26",
    embarked: "S",
    boat: null,
    body: null,
    "home.dest": "Montreal, PQ / Chesterville, ON"
    },
    {
    id: 4,
    class: "1",
    survived: false,
    name: "Allison, Mr. Hudson Joshua Creighton",
    gender: "male",
    age: 30,
    sibsp: "1",
    parch: "2",
    ticket: "113781",
    fare: "151.55",
    cabin: "C22 C26",
    embarked: "S",
    boat: null,
    body: "135",
    "home.dest": "Montreal, PQ / Chesterville, ON"
    },
    {
    id: 5,
    class: "1",
    survived: false,
    name: "Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",
    gender: "female",
    age: 25,
    sibsp: "1",
    parch: "2",
    ticket: "113781",
    fare: "151.55",
    cabin: "C22 C26",
    embarked: "S",
    boat: null,
    body: null,
    "home.dest": "Montreal, PQ / Chesterville, ON"
    },  
    {
    id: 6,
    class: "1",
    survived: true,
    name: "Anderson, Mr. Harry",
    gender: "male",
    age: 48,
    sibsp: "0",
    parch: "0",
    ticket: "19952",
    fare: "26.55",
    cabin: "E12",
    embarked: "S",
    boat: "3",
    body: null,
    "home.dest": "New York, NY"
    },
    {
        id: 1,
        class: "1",
        survived: true,
        name: "Allen, Miss. Elisabeth Walton",
        gender: "female",
        age: 29,
        sibsp: "0",
        parch: "0",
        ticket: "24160",
        fare: "211.3375",
        cabin: "B5",
        embarked: "S",
        boat: "2",
        body: null,
        'home.dest': "St Louis, MO"
        },
        {
        id: 2,
        class: "1",
        survived: true,
        name: "Allison, Master. Hudson Trevor",
        gender: "male",
        age: 0.9167,
        sibsp: "1",
        parch: "2",
        ticket: "113781",
        fare: "151.55",
        cabin: "C22 C26",
        embarked: "S",
        boat: "11",
        body: null,
        "home.dest": "Montreal, PQ / Chesterville, ON"
        },
        {
        id: 3,
        class: "1",
        survived: false,
        name: "Allison, Miss. Helen Loraine",
        gender: "female",
        age: 2,
        sibsp: "1",
        parch: "2",
        ticket: "113781",
        fare: "151.55",
        cabin: "C22 C26",
        embarked: "S",
        boat: null,
        body: null,
        "home.dest": "Montreal, PQ / Chesterville, ON"
        },
        {
        id: 4,
        class: "1",
        survived: false,
        name: "Allison, Mr. Hudson Joshua Creighton",
        gender: "male",
        age: 30,
        sibsp: "1",
        parch: "2",
        ticket: "113781",
        fare: "151.55",
        cabin: "C22 C26",
        embarked: "S",
        boat: null,
        body: "135",
        "home.dest": "Montreal, PQ / Chesterville, ON"
        },
        {
        id: 5,
        class: "1",
        survived: false,
        name: "Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",
        gender: "female",
        age: 25,
        sibsp: "1",
        parch: "2",
        ticket: "113781",
        fare: "151.55",
        cabin: "C22 C26",
        embarked: "S",
        boat: null,
        body: null,
        "home.dest": "Montreal, PQ / Chesterville, ON"
        },  
        {
        id: 6,
        class: "1",
        survived: true,
        name: "Anderson, Mr. Harry",
        gender: "male",
        age: 48,
        sibsp: "0",
        parch: "0",
        ticket: "19952",
        fare: "26.55",
        cabin: "E12",
        embarked: "S",
        boat: "3",
        body: null,
        "home.dest": "New York, NY"
        },
        {
        id: 1,
        class: "1",
        survived: true,
        name: "Allen, Miss. Elisabeth Walton",
        gender: "female",
        age: 29,
        sibsp: "0",
        parch: "0",
        ticket: "24160",
        fare: "211.3375",
        cabin: "B5",
        embarked: "S",
        boat: "2",
        body: null,
        'home.dest': "St Louis, MO"
        },
        {
        id: 2,
        class: "1",
        survived: true,
        name: "Allison, Master. Hudson Trevor",
        gender: "male",
        age: 0.9167,
        sibsp: "1",
        parch: "2",
        ticket: "113781",
        fare: "151.55",
        cabin: "C22 C26",
        embarked: "S",
        boat: "11",
        body: null,
        "home.dest": "Montreal, PQ / Chesterville, ON"
        },
        {
        id: 3,
        class: "1",
        survived: false,
        name: "Allison, Miss. Helen Loraine",
        gender: "female",
        age: 2,
        sibsp: "1",
        parch: "2",
        ticket: "113781",
        fare: "151.55",
        cabin: "C22 C26",
        embarked: "S",
        boat: null,
        body: null,
        "home.dest": "Montreal, PQ / Chesterville, ON"
        },
        {
        id: 4,
        class: "1",
        survived: false,
        name: "Allison, Mr. Hudson Joshua Creighton",
        gender: "male",
        age: 30,
        sibsp: "1",
        parch: "2",
        ticket: "113781",
        fare: "151.55",
        cabin: "C22 C26",
        embarked: "S",
        boat: null,
        body: "135",
        "home.dest": "Montreal, PQ / Chesterville, ON"
        },
        {
        id: 5,
        class: "1",
        survived: false,
        name: "Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",
        gender: "female",
        age: 25,
        sibsp: "1",
        parch: "2",
        ticket: "113781",
        fare: "151.55",
        cabin: "C22 C26",
        embarked: "S",
        boat: null,
        body: null,
        "home.dest": "Montreal, PQ / Chesterville, ON"
        },  
        {
        id: 6,
        class: "1",
        survived: true,
        name: "Anderson, Mr. Harry",
        gender: "male",
        age: 48,
        sibsp: "0",
        parch: "0",
        ticket: "19952",
        fare: "26.55",
        cabin: "E12",
        embarked: "S",
        boat: "3",
        body: null,
        "home.dest": "New York, NY"
        },
        {
            id: 1,
            class: "1",
            survived: true,
            name: "Allen, Miss. Elisabeth Walton",
            gender: "female",
            age: 29,
            sibsp: "0",
            parch: "0",
            ticket: "24160",
            fare: "211.3375",
            cabin: "B5",
            embarked: "S",
            boat: "2",
            body: null,
            'home.dest': "St Louis, MO"
            },
            {
            id: 2,
            class: "1",
            survived: true,
            name: "Allison, Master. Hudson Trevor",
            gender: "male",
            age: 0.9167,
            sibsp: "1",
            parch: "2",
            ticket: "113781",
            fare: "151.55",
            cabin: "C22 C26",
            embarked: "S",
            boat: "11",
            body: null,
            "home.dest": "Montreal, PQ / Chesterville, ON"
            },
            {
            id: 3,
            class: "1",
            survived: false,
            name: "Allison, Miss. Helen Loraine",
            gender: "female",
            age: 2,
            sibsp: "1",
            parch: "2",
            ticket: "113781",
            fare: "151.55",
            cabin: "C22 C26",
            embarked: "S",
            boat: null,
            body: null,
            "home.dest": "Montreal, PQ / Chesterville, ON"
            },
            {
            id: 4,
            class: "1",
            survived: false,
            name: "Allison, Mr. Hudson Joshua Creighton",
            gender: "male",
            age: 30,
            sibsp: "1",
            parch: "2",
            ticket: "113781",
            fare: "151.55",
            cabin: "C22 C26",
            embarked: "S",
            boat: null,
            body: "135",
            "home.dest": "Montreal, PQ / Chesterville, ON"
            },
            {
            id: 5,
            class: "1",
            survived: false,
            name: "Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",
            gender: "female",
            age: 25,
            sibsp: "1",
            parch: "2",
            ticket: "113781",
            fare: "151.55",
            cabin: "C22 C26",
            embarked: "S",
            boat: null,
            body: null,
            "home.dest": "Montreal, PQ / Chesterville, ON"
            },  
            {
            id: 6,
            class: "1",
            survived: true,
            name: "Anderson, Mr. Harry",
            gender: "male",
            age: 48,
            sibsp: "0",
            parch: "0",
            ticket: "19952",
            fare: "26.55",
            cabin: "E12",
            embarked: "S",
            boat: "3",
            body: null,
            "home.dest": "New York, NY"
            },
            {
            id: 1,
            class: "1",
            survived: true,
            name: "Allen, Miss. Elisabeth Walton",
            gender: "female",
            age: 29,
            sibsp: "0",
            parch: "0",
            ticket: "24160",
            fare: "211.3375",
            cabin: "B5",
            embarked: "S",
            boat: "2",
            body: null,
            'home.dest': "St Louis, MO"
            },
            {
            id: 2,
            class: "1",
            survived: true,
            name: "Allison, Master. Hudson Trevor",
            gender: "male",
            age: 0.9167,
            sibsp: "1",
            parch: "2",
            ticket: "113781",
            fare: "151.55",
            cabin: "C22 C26",
            embarked: "S",
            boat: "11",
            body: null,
            "home.dest": "Montreal, PQ / Chesterville, ON"
            },
            {
            id: 3,
            class: "1",
            survived: false,
            name: "Allison, Miss. Helen Loraine",
            gender: "female",
            age: 2,
            sibsp: "1",
            parch: "2",
            ticket: "113781",
            fare: "151.55",
            cabin: "C22 C26",
            embarked: "S",
            boat: null,
            body: null,
            "home.dest": "Montreal, PQ / Chesterville, ON"
            },
            {
            id: 4,
            class: "1",
            survived: false,
            name: "Allison, Mr. Hudson Joshua Creighton",
            gender: "male",
            age: 30,
            sibsp: "1",
            parch: "2",
            ticket: "113781",
            fare: "151.55",
            cabin: "C22 C26",
            embarked: "S",
            boat: null,
            body: "135",
            "home.dest": "Montreal, PQ / Chesterville, ON"
            },
            {
            id: 5,
            class: "1",
            survived: false,
            name: "Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",
            gender: "female",
            age: 25,
            sibsp: "1",
            parch: "2",
            ticket: "113781",
            fare: "151.55",
            cabin: "C22 C26",
            embarked: "S",
            boat: null,
            body: null,
            "home.dest": "Montreal, PQ / Chesterville, ON"
            },  
            {
            id: 6,
            class: "1",
            survived: true,
            name: "Anderson, Mr. Harry",
            gender: "male",
            age: 48,
            sibsp: "0",
            parch: "0",
            ticket: "19952",
            fare: "26.55",
            cabin: "E12",
            embarked: "S",
            boat: "3",
            body: null,
            "home.dest": "New York, NY"
            },
            {
                id: 1,
                class: "1",
                survived: true,
                name: "Allen, Miss. Elisabeth Walton",
                gender: "female",
                age: 29,
                sibsp: "0",
                parch: "0",
                ticket: "24160",
                fare: "211.3375",
                cabin: "B5",
                embarked: "S",
                boat: "2",
                body: null,
                'home.dest': "St Louis, MO"
                },
                {
                id: 2,
                class: "1",
                survived: true,
                name: "Allison, Master. Hudson Trevor",
                gender: "male",
                age: 0.9167,
                sibsp: "1",
                parch: "2",
                ticket: "113781",
                fare: "151.55",
                cabin: "C22 C26",
                embarked: "S",
                boat: "11",
                body: null,
                "home.dest": "Montreal, PQ / Chesterville, ON"
                },
                {
                id: 3,
                class: "1",
                survived: false,
                name: "Allison, Miss. Helen Loraine",
                gender: "female",
                age: 2,
                sibsp: "1",
                parch: "2",
                ticket: "113781",
                fare: "151.55",
                cabin: "C22 C26",
                embarked: "S",
                boat: null,
                body: null,
                "home.dest": "Montreal, PQ / Chesterville, ON"
                },
                {
                id: 4,
                class: "1",
                survived: false,
                name: "Allison, Mr. Hudson Joshua Creighton",
                gender: "male",
                age: 30,
                sibsp: "1",
                parch: "2",
                ticket: "113781",
                fare: "151.55",
                cabin: "C22 C26",
                embarked: "S",
                boat: null,
                body: "135",
                "home.dest": "Montreal, PQ / Chesterville, ON"
                },
                {
                id: 5,
                class: "1",
                survived: false,
                name: "Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",
                gender: "female",
                age: 25,
                sibsp: "1",
                parch: "2",
                ticket: "113781",
                fare: "151.55",
                cabin: "C22 C26",
                embarked: "S",
                boat: null,
                body: null,
                "home.dest": "Montreal, PQ / Chesterville, ON"
                },  
                {
                id: 6,
                class: "1",
                survived: true,
                name: "Anderson, Mr. Harry",
                gender: "male",
                age: 48,
                sibsp: "0",
                parch: "0",
                ticket: "19952",
                fare: "26.55",
                cabin: "E12",
                embarked: "S",
                boat: "3",
                body: null,
                "home.dest": "New York, NY"
                },
                {
                id: 1,
                class: "1",
                survived: true,
                name: "Allen, Miss. Elisabeth Walton",
                gender: "female",
                age: 29,
                sibsp: "0",
                parch: "0",
                ticket: "24160",
                fare: "211.3375",
                cabin: "B5",
                embarked: "S",
                boat: "2",
                body: null,
                'home.dest': "St Louis, MO"
                },
                {
                id: 2,
                class: "1",
                survived: true,
                name: "Allison, Master. Hudson Trevor",
                gender: "male",
                age: 0.9167,
                sibsp: "1",
                parch: "2",
                ticket: "113781",
                fare: "151.55",
                cabin: "C22 C26",
                embarked: "S",
                boat: "11",
                body: null,
                "home.dest": "Montreal, PQ / Chesterville, ON"
                },
                {
                id: 3,
                class: "1",
                survived: false,
                name: "Allison, Miss. Helen Loraine",
                gender: "female",
                age: 2,
                sibsp: "1",
                parch: "2",
                ticket: "113781",
                fare: "151.55",
                cabin: "C22 C26",
                embarked: "S",
                boat: null,
                body: null,
                "home.dest": "Montreal, PQ / Chesterville, ON"
                },
                {
                id: 4,
                class: "1",
                survived: false,
                name: "Allison, Mr. Hudson Joshua Creighton",
                gender: "male",
                age: 30,
                sibsp: "1",
                parch: "2",
                ticket: "113781",
                fare: "151.55",
                cabin: "C22 C26",
                embarked: "S",
                boat: null,
                body: "135",
                "home.dest": "Montreal, PQ / Chesterville, ON"
                },
                {
                id: 5,
                class: "1",
                survived: false,
                name: "Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",
                gender: "female",
                age: 25,
                sibsp: "1",
                parch: "2",
                ticket: "113781",
                fare: "151.55",
                cabin: "C22 C26",
                embarked: "S",
                boat: null,
                body: null,
                "home.dest": "Montreal, PQ / Chesterville, ON"
                },  
                {
                id: 6,
                class: "1",
                survived: true,
                name: "Anderson, Mr. Harry",
                gender: "male",
                age: 48,
                sibsp: "0",
                parch: "0",
                ticket: "19952",
                fare: "26.55",
                cabin: "E12",
                embarked: "S",
                boat: "3",
                body: null,
                "home.dest": "New York, NY"
                },
]